### PR TITLE
Additional commit to remove need for Internet connection during module startup

### PR DESCRIPTION
**Pull request by ssmusoke**

### CODE REVIEW

**Comment by dkayiwa** [comment]
Are you forgetting to do something? Your PR seems to have lots more commits than it should. :)

**Comment by ssmusoke** [comment]
@dkayiwa Struggling with squashing - can you squash as you merge?

**Comment by dkayiwa** [comment]
The challenge with these is that they take longer to review because i need to review each individual commit to see whatsup in there.

**Comment by dkayiwa** [comment]
@ssmusoke for a change as simple as this, your life would be made easier if you just start by reverting them, then ensure that you have the latest upstream changes. Now you can add your changes back in and create a new pull request.

**Comment by ssmusoke** [comment]
@dkayiwa Noted

**Pull request closed without merging**
