### PR TITLE
Fixing problem where running on platform 2.x required an internet connection

### PR DESCRIPTION
**Pull request by ssmusoke**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ssmusoke is this different from the commits i made earlier on?

**Comment by dkayiwa** [comment]
The PR also seems to have multiple commits dealing with different things.

**Comment by ssmusoke** [comment]
@dkayiwa I had to rebase the branch that I had locally - hence the change later. Can the commits be squashed at merge?

**Comment by dkayiwa** [comment]
Are they dealing with something different from what i addressed in the earlier commits?

**Comment by ssmusoke** [comment]
@dkayiwa I have cleaned up the commits - they are now okay - the only change is to the DTD

**Pull request merged**
